"use client";
import { FileText, Copy, Check, Download, Loader2 } from "lucide-react";
import { useState, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

const DocsPanel = ({ documentation, isLearningMode = false }) => {
    const [copied, setCopied] = useState(false);
    const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);
    const contentRef = useRef(null);

    const handleCopy = () => {
        if (!documentation) return;
        navigator.clipboard.writeText(documentation);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const handleDownloadPdf = async () => {
        if (!documentation || !contentRef.current) return;

        setIsGeneratingPdf(true);

        try {
            // Dynamic import to avoid SSR issues
            const html2pdf = (await import('html2pdf.js')).default;

            // Create a styled container for PDF generation
            const pdfContainer = document.createElement('div');
            pdfContainer.innerHTML = `
                <div style="
                    font-family: 'Georgia', 'Times New Roman', serif;
                    padding: 40px;
                    background: linear-gradient(135deg, #fefefe 0%, #f8f9fa 100%);
                    color: #1a1a2e;
                    line-height: 1.8;
                    max-width: 100%;
                ">
                    <div style="
                        border-bottom: 3px solid #667eea;
                        padding-bottom: 20px;
                        margin-bottom: 30px;
                    ">
                        <h1 style="
                            font-size: 28px;
                            font-weight: 700;
                            color: #1a1a2e;
                            margin: 0 0 8px 0;
                            letter-spacing: -0.5px;
                        ">📚 Code Documentation</h1>
                        <p style="
                            font-size: 12px;
                            color: #666;
                            margin: 0;
                        ">Generated by CodeRev • ${new Date().toLocaleDateString('en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric'
            })}</p>
                    </div>
                    <div class="pdf-content">
                        ${contentRef.current.innerHTML}
                    </div>
                    <div style="
                        margin-top: 40px;
                        padding-top: 20px;
                        border-top: 1px solid #e0e0e0;
                        text-align: center;
                        font-size: 10px;
                        color: #888;
                    ">
                        Made with ❤️ by CodeRev Learning Mode
                    </div>
                </div>
            `;

            // Apply PDF-friendly styles to the content
            const style = document.createElement('style');
            style.textContent = `
                .pdf-content h1, .pdf-content h2, .pdf-content h3 {
                    color: #1a1a2e !important;
                    margin-top: 24px !important;
                    margin-bottom: 12px !important;
                }
                .pdf-content h1 { 
                    font-size: 22px !important; 
                    border-bottom: 2px solid #667eea;
                    padding-bottom: 8px;
                }
                .pdf-content h2 { 
                    font-size: 18px !important;
                    color: #4a5568 !important;
                }
                .pdf-content h3 { 
                    font-size: 15px !important;
                    color: #667eea !important;
                }
                .pdf-content p {
                    color: #2d3748 !important;
                    font-size: 13px !important;
                    margin-bottom: 12px !important;
                    text-align: justify;
                }
                .pdf-content ul, .pdf-content ol {
                    color: #2d3748 !important;
                    padding-left: 20px !important;
                    margin-bottom: 12px !important;
                }
                .pdf-content li {
                    margin-bottom: 6px !important;
                    font-size: 13px !important;
                }
                .pdf-content code {
                    background: #e8eef3 !important;
                    color: #d63384 !important;
                    padding: 2px 6px !important;
                    border-radius: 4px !important;
                    font-size: 12px !important;
                    font-family: 'Consolas', 'Monaco', monospace !important;
                }
                .pdf-content pre, .pdf-content pre code {
                    background: #1e1e2e !important;
                    color: #cdd6f4 !important;
                    padding: 16px !important;
                    border-radius: 8px !important;
                    overflow-x: auto !important;
                    font-size: 11px !important;
                    line-height: 1.6 !important;
                }
                .pdf-content blockquote {
                    border-left: 4px solid #667eea !important;
                    padding-left: 16px !important;
                    margin: 16px 0 !important;
                    font-style: italic !important;
                    color: #4a5568 !important;
                    background: #f7fafc !important;
                    padding: 12px 16px !important;
                    border-radius: 0 8px 8px 0 !important;
                }
            `;
            pdfContainer.appendChild(style);

            const opt = {
                margin: [10, 10, 10, 10],
                filename: `CodeRev_Documentation_${new Date().toISOString().split('T')[0]}.pdf`,
                image: { type: 'jpeg', quality: 0.98 },
                html2canvas: {
                    scale: 2,
                    useCORS: true,
                    logging: false,
                },
                jsPDF: {
                    unit: 'mm',
                    format: 'a4',
                    orientation: 'portrait'
                },
                pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
            };

            await html2pdf().set(opt).from(pdfContainer).save();
        } catch (error) {
            console.error('Failed to generate PDF:', error);
            // Fallback: open print dialog
            const printWindow = window.open('', '_blank');
            if (printWindow) {
                printWindow.document.write(`
                    <html>
                        <head>
                            <title>CodeRev Documentation</title>
                            <style>
                                body { font-family: Georgia, serif; padding: 40px; line-height: 1.8; }
                                h1, h2, h3 { color: #1a1a2e; }
                                code { background: #f0f0f0; padding: 2px 6px; border-radius: 4px; }
                            </style>
                        </head>
                        <body>
                            <h1>📚 Code Documentation</h1>
                            ${contentRef.current.innerHTML}
                        </body>
                    </html>
                `);
                printWindow.document.close();
                printWindow.print();
            }
        } finally {
            setIsGeneratingPdf(false);
        }
    };

    return (
        <div className="w-full h-full flex flex-col bg-zinc-950">
            {/* Header */}
            <div className="flex items-center justify-between px-4 py-2 border-b border-white/10 bg-zinc-900/50">
                <div className="flex items-center gap-2">
                    <FileText size={14} className="text-zinc-400" />
                    <span className="text-xs font-medium text-zinc-300">Documentation</span>
                </div>

                <div className="flex items-center gap-1">
                    {/* PDF Download Button - Only in Learning Mode */}
                    {isLearningMode && (
                        <button
                            onClick={handleDownloadPdf}
                            disabled={!documentation || isGeneratingPdf}
                            className="flex items-center gap-1.5 px-2.5 py-1.5 text-zinc-300 hover:text-white hover:bg-gradient-to-r hover:from-violet-600/20 hover:to-indigo-600/20 rounded-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed border border-transparent hover:border-violet-500/30"
                            title="Download as PDF Notes"
                        >
                            {isGeneratingPdf ? (
                                <Loader2 size={14} className="animate-spin" />
                            ) : (
                                <Download size={14} />
                            )}
                            <span className="text-xs font-medium">PDF</span>
                        </button>
                    )}

                    <button
                        onClick={handleCopy}
                        disabled={!documentation}
                        className="p-1.5 text-zinc-400 hover:text-white hover:bg-white/10 rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                        title="Copy Documentation"
                    >
                        {copied ? <Check size={14} className="text-green-400" /> : <Copy size={14} />}
                    </button>
                </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-auto p-4 text-sm">
                {documentation ? (
                    <div ref={contentRef} className="prose prose-invert prose-sm max-w-none">
                        <ReactMarkdown
                            remarkPlugins={[remarkGfm]}
                            components={{
                                h1: ({ node, ...props }) => <h1 className="text-xl font-bold text-zinc-100 mb-4 pb-2 border-b border-white/10" {...props} />,
                                h2: ({ node, ...props }) => <h2 className="text-lg font-semibold text-zinc-200 mt-6 mb-3" {...props} />,
                                h3: ({ node, ...props }) => <h3 className="text-base font-medium text-zinc-300 mt-4 mb-2" {...props} />,
                                p: ({ node, ...props }) => <p className="text-zinc-400 leading-relaxed mb-4" {...props} />,
                                ul: ({ node, ...props }) => <ul className="list-disc list-inside space-y-1 text-zinc-400 mb-4 ml-2" {...props} />,
                                ol: ({ node, ...props }) => <ol className="list-decimal list-inside space-y-1 text-zinc-400 mb-4 ml-2" {...props} />,
                                li: ({ node, ...props }) => <li className="text-zinc-400" {...props} />,
                                code: ({ node, inline, className, children, ...props }) => {
                                    return inline ? (
                                        <code className="bg-zinc-900 px-1.5 py-0.5 rounded text-xs font-mono text-zinc-300 border border-white/10" {...props}>
                                            {children}
                                        </code>
                                    ) : (
                                        <code className="block bg-zinc-900 p-3 rounded-lg text-xs font-mono text-zinc-300 border border-white/10 overflow-x-auto my-4" {...props}>
                                            {children}
                                        </code>
                                    );
                                },
                                blockquote: ({ node, ...props }) => <blockquote className="border-l-2 border-zinc-700 pl-4 italic text-zinc-500 my-4" {...props} />,
                            }}
                        >
                            {documentation}
                        </ReactMarkdown>
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center h-full text-zinc-600 gap-2">
                        <FileText size={24} className="opacity-50" />
                        <p className="text-xs">Generate docs to see them here</p>
                    </div>
                )}
            </div>
        </div>
    );
};

export default DocsPanel;
